version: "3.3"

services:
  app:
    privileged: true
    image: ocordes/home-reverse-proxy:0.9.6.1
    restart: always
    networks:
      - web
    expose:
      - "8080"
    ports:
      - 8080:8080
    labels:
      #- "traefik.docker.network=web"
      #- "traefik.enable=true"
      #- "traefik.http.routers.hrp.entrypoints=http"
      #- "traefik.http.routers.hrp.rule=Host(`hrp.docker.astro.uni-bonn.de`)"
      #- "traefik.http.middlewares.hrp-https-redirect.redirectscheme.scheme=https"
      #- "traefik.http.routers.hrp.middlewares=hrp-https-redirect"
      #- "traefik.http.routers.hrp-secure.entrypoints=https"
      #- "traefik.http.routers.hrp-secure.rule=Host(`hrp.docker.astro.uni-bonn.de`)"
      #- "traefik.http.routers.hrp-secure.tls=true"
      #- "traefik.http.routers.hrp-secure.tls.certresolver=http"
      #- "traefik.http.routers.hrp-secure.service=hrp"
      #- "traefik.http.services.hrp.loadbalancer.server.port=8080"
      #- "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:astro.uni-bonn.de;PathPrefix:/~"
      - "traefik.port=8080"
      - "traefik.docker.network=web"
    volumes:
      - ./hrp_config_docker.yaml:/hrp_config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - /users:/users:shared
      - /vol:/vol:shared
     

networks:
  web:
    external: true

