debug: false
port: 8080

docker:
  # image for the container
  image: registry.gitlab.com/ocordes/userwebsite:latest
  # all containers are started in the specific subnet, 
  # aka network sandboxing
  network: web

cull:
  enabled: true
  every: 600
  timeout: 1800

ldap:
  server: ldaps://ldap2.astro.uni-bonn.de
  base: ou=People,dc=astro,dc=uni-bonn,dc=de
  user_attr: uid

