debug: false
port: 8080

docker:
  # image for the container
  image: registry.gitlab.com/ocordes/userwebsite:latest
  # all containers are started in the specific subnet, 
  # aka network sandboxing
  network: proxy

cull:
  enabled: true
  every: 30
  timeout: 30
  #every: 600
  #timeout: 1800

ldap:
  server: ldap2.astro.uni-bonn.de
  dn: 'uid={username},ou=People,dc=astro,dc=uni-bonn,dc=de'

